### ISSUE TITLE
Site too slow

### ISSUE THREAD

**Issue by tiagonmas** [banco-alimentar/alimentestaideia.pt#693]
**Describe the bug**
Pages are taking too long to load
![image](https://user-images.githubusercontent.com/42462/194411564-c6cd7f9c-afd0-40ba-a975-a127dfbd3b89.png)

**Comment by tiagonmas** [comment]
Moved dev to production but still things are running slow. eg DonationHistory
![image](https://user-images.githubusercontent.com/42462/194642910-ad05a877-9320-4671-b024-feaebbea8204.png)

**Comment by tiagonmas** [comment]
Eg loading subscriptions details
![image](https://user-images.githubusercontent.com/42462/194702924-9402dd7c-f552-4013-9af0-046b5a8eb492.png)

**Comment by tiagonmas** [comment]
is sql a problem ? 
![image](https://user-images.githubusercontent.com/42462/194752917-569131a2-d9fd-4957-804d-8a745589ed9d.png)

**Comment by tiagonmas** [comment]
Many pages are taking too long in DataTAbleData and this one is saying there are duplicate calls
![image](https://user-images.githubusercontent.com/42462/194753147-e5aa09c0-b8bf-4690-91fd-5aabb4d1816a.png)

**Comment by guerrerotook** [comment]
Over all the performance of the web site is ok. SQL is not a problem because right now we are running in the basic mode for SQL and the performance is ok. 

About the duplicate SQL calls, you where in the details for the subscriptions and we were making similar calls to the database, nothing to worry about. 

The main driver for the bad performance was the StaticFileProvider where files for the tenant where backed up in a Azure Storage Account and that was making the server to all threads to wait because all threads where making HTTP request to Azure Storage Blob, I made a optimization by enabling a cache in the hard drive of the VM where the website is running and now the performance should be ok.

**Comment by tiagonmas** [comment]
This is the AVG of last 24h in production. If you put 95% numbers go up to minute :(
![image](https://user-images.githubusercontent.com/42462/194779022-1628a3d4-49aa-4de2-a99e-84e2aeeadc1f.png)
