### ISSUE TITLE
[Doar+]  Invoice is always updating the date, to today

### ISSUE THREAD

**Issue by tiagonmas** [banco-alimentar/alimentestaideia.pt#760]
**Describe the bug**
Whenever I call GetInvoice, the date is updated to today and not the date of when the invoice was originally created

**To Reproduce**
1. Create an invoce. Note the date.
2. Ask to see the invoice again tomorrow.
3. Confirm that the date is not the same as original invoice, but is now set as today

**Comment by guerrerotook** [comment]
@tiagonmas, this is not a bug, because we are building debug for the developer slot, this code is active.

https://github.com/banco-alimentar/alimentestaideia.pt/blob/e8a931ed4656222a2e9772d287fad54edaaf241f/BancoAlimentar.AlimentaEstaIdeia.Web/Areas/Identity/Pages/Account/Manage/GenerateInvoice.cshtml.cs#L150

So every time you request the invoice a new one will be generated, but that is not active in release or production. So you don't need to look a this right now.

**Comment by tiagonmas** [comment]
Good Catch. But I think this is not happening in https://dev.alimentestaideia.pt/ ... it might not have the same DEBUG setting. Will close the issue then
