### ISSUE TITLE
investigate Alerts on errors in production

### ISSUE THREAD

**Issue by tiagonmas** [banco-alimentar/alimentestaideia.pt#779]
**Describe the bug**
Keep on getting alerts from app insights but not for "serious" issues ...

```
// Failed operations 
// Calculate how many times operations failed, and how many users were impacted. 
// To create an alert for this query, click '+ New alert rule'
requests
| where success == false and cloud_RoleName == 'alimentaestaideia' and operation_Name != 'GET /status'
| summarize failedCount=sum(itemCount), impactedUsers=dcount(user_Id) by operation_Name
| order by failedCount desc
```

**Comment by guerrerotook** [comment]
There are some errors in the production website, those errors are related to the login process. 
<img width="367" alt="image" src="https://github.com/user-attachments/assets/86f1568a-edac-4a91-855b-904461947120">

And asp.net core be unable to unprotecting the session cookie. This is something that we can ignore.

**Comment by guerrerotook** [comment]
The three existing exceptions were related to login issues. 

<img width="859" alt="image" src="https://github.com/user-attachments/assets/642408b6-103d-4eff-8889-cda4a1001404">

I think that we can safely ignore this from now on.

**Comment by guerrerotook** [comment]
Well this is a difficult question because those are small exceptions counts. But for example, disabling the exceptions for the login and register is something that we don't want, because if in the future something happens then and those notification are disabled, we will not be notified of what happen. 

I think the best approach to this is to look at those alerts on a ad-hoc basic and the decide what to do! For this particular issue I think that we should close it and that's it.

**Comment by tiagonmas** [comment]
I just updated the alert to only happen if it is more than 2 per hour. If it is a serious bug it will happen more ofter ... I hope :).
